### ISSUE TITLE
Update the theme

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-gutenberg#18]
Task List:

- [x] [Update theme styles to match designs](https://github.com/WordPress/wporg-gutenberg/issues/20)
- [x] [Move front end editor modifications out of functions.php](https://github.com/StevenDufresne/wporg-gutenberg/issues/13)
- [x] [Clean up unfinished theme work](https://github.com/StevenDufresne/wporg-gutenberg/issues/12)
